### ISSUE TITLE
500 Peer Not Authorized

### ISSUE THREAD

**Issue by stovak** [mocleiri/github-oauth-plugin#11]
Seems like I need to import some certificate into somewhere...???

Try to log in via github. URl's are correct on Github side. When accessing URL:

I get:
Error 500
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:371)
    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:390)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
    at org.jenkinsci.plugins.GithubSecurityRealm.doFinishLogin(GithubSecurityRealm.java:278)

Interestingly, if I change the github address to Http:// instead of https:// I get a different error.

**Comment by cyberswat** [comment]
just going to throw it out there that I'm having the same issue ... I even compiled http://code.google.com/p/java-use-examples/source/browse/trunk/src/com/aw/ad/util/InstallCert.java and imported the certificates from github

**Comment by andrewlmurray** [comment]
I am seeing this issue as well

**Comment by andrewlmurray** [comment]
FYI to everyone on this issue. I added -Djavax.net.debug=ssl to my jenkins startup and saw that the jdk was claiming that githubs certs were not signed by a valid CA. (which is obviously bogus)

Upon further investigation I saw that the box I was deploying on was running openjdk and not the sun jdk. I'm guessing the trust certs shipped with the version of openjdk I was using are out of date. 

I installed the sun jdk and ran there and all works as it should. This is almost certainly an issue with your jdk installation.

**Comment by stovak** [comment]
is there a way to import a correct cert into open java?

**Comment by cyberswat** [comment]
If there is I haven't found it ... I needed to import the github certs just to get jenkins to work at all with github and did that some time ago ... The InstallCert program did that well.  I can appreciate that "your running the wrong software" is a great answer to a problem, but it's completely not useful here.

**Comment by andrewlmurray** [comment]
Right - I'm just saying that however olay build of openJDK 1.6 was
configured it didn't recognize the CA that signed githubs certificate as
being valid - which is obviously wrong.

I didn't look at it any further as I have no problem running the sun JDK
and it fixed the problem.

I meant my note just to indicate that this isn't a bug with the plugin at
all - but rather a config issue with the JDK.

On Saturday, January 14, 2012, Kevin Bridges <
reply@reply.github.com>
wrote:

**Comment by p0deje** [comment]
I confirm that such problem exists with OpenJDK and it's resolved by using Oracle/Sun JRE

**Comment by mocleiri** [comment]
Thanks for investigating this issue.

Because it is not fixable by the plugin itself I am closing this issue.
