### ISSUE TITLE
java.lang.NullPointerException GithubRequireOrganizationMembershipACL

### ISSUE THREAD

**Issue by hedgehog** [mocleiri/github-oauth-plugin#12]
Apologies if this is not the right plugin.  If not could you point me in the right direction?

With this command

```
java -jar /home/vagrant/jenkins-cli.jar -s http://lucid64-base:8080 create-job staging < /tmp/job_staging.xml
```

This is the error:

```
 java.lang.NullPointerException
    at org.jenkinsci.plugins.GithubRequireOrganizationMembershipACL.hasPermission(GithubRequireOrganizationMembershipACL.java:126)
    at hudson.security.ACL.checkPermission(ACL.java:52)
    at hudson.model.Node.checkPermission(Node.java:381)
    at hudson.cli.CLICommand.main(CLICommand.java:186)
    at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:274)
    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:255)
    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:215)
    at hudson.remoting.UserRequest.perform(UserRequest.java:118)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:287)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
: stdout
```

**Comment by mocleiri** [comment]
This is the right plugin.  

I haven't used the cli before but the plugin expects everyone to be authorized through the github-oauth mechanism.

Since the cli is not a web app it is not working properly.

The wiki page on the cli says one version supports public key authorization.  So one fix might be to add a place to specify a public key to trust when used from the cli.

Have you used public key authorization for the cli before?  I am having trouble finding an example plugin that sets up that type of access control.

**Comment by mocleiri** [comment]
Ok I found that the functionality is built into Jenkins.

Can you go to http://lucid64-base:8080/me/configure in a web browser.  Then you can associate an ssh public key to your user account.

Then you can use this key with the cli and it should work.  Unless there is something that the plugin itself needs to implement.

Link: https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+CLI (see the working with credentials section)

**Comment by hedgehog** [comment]
Ouch, in the meantime I resorted to creating jobs by creating the folder and copying in the config.xml.  Seems to be the most reliable and least painful mechanism at the moment.  Anyway I'm closing this issue since It seems there is no bug with this plugin.  Once I create the jobs, as described, it seems to load this plugin fine.

**Comment by RSO** [comment]
Trying to run the CLI with Public key authentication results in the following error:

```
Exception in thread "main" java.io.EOFException
    at java.io.DataInputStream.readBoolean(DataInputStream.java:244)
    at hudson.cli.Connection.readBoolean(Connection.java:95)
    at hudson.cli.CLI.authenticate(CLI.java:634)
    at hudson.cli.CLI._main(CLI.java:474)
    at hudson.cli.CLI.main(CLI.java:384)
```

**Comment by SteveDonie** [comment]
@RSO - I have Jenkins v 1.518 and we are using GutHub OAth plugin 0.13.1. 

I have my public key uploaded to Jenkins - I logged in to the web UI and then went to http://myjenkinsurl/me/configure and pasted in my id_rsa.pub contents. When I then try to log in with java -jar jenkins_cli.jar -i ~/.ssh/id_rsa I get the same stack trace you pasted in:

Exception in thread "main" java.io.EOFException
    at java.io.DataInputStream.readBoolean(DataInputStream.java:244)
    at hudson.cli.Connection.readBoolean(Connection.java:95)
    at hudson.cli.CLI.authenticate(CLI.java:634)

Were you able to get logged in, and if so what did you do?

**Comment by RSO** [comment]
We decided to not use the Oauth plugin. I can't really recall what else we decided to do, if you want I can go take a look!
