### ISSUE TITLE
[SUPPORT] Access github auth token from cli or api

### ISSUE THREAD

**Issue by patcon** [mocleiri/github-oauth-plugin#32]
Just shoo me away if this a more general jenkins-related question, but wondering how I can use some programmatic means to get the token out of jenkins for use in other code. Assuming I need some way to run/expose this from the command-line:
https://github.com/mocleiri/github-oauth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/GithubAuthenticationToken.java#L84

To give context, trying to use a config management tool (Chef) to access the github API and fetch each auth'd github user's SSH keys to the machine. Seems like an easier way than independently adding the keys somewhere in the config management instructions :)

**Comment by marcospereira** [comment]
@patcon 

Not sure if it is related, but I think the `org.jenkinsci.plugins.GithubSecurityRealm` must be able to handle user api token provided by jenkins itself (you can access it clicking in your username and then "configure"). Currently, trying to access API using this token results in a `NullPointerException`:

```
ava.lang.NullPointerException
    at org.jenkinsci.plugins.GithubSecurityRealm.loadGroupByGroupname(GithubSecurityRealm.java:459)
    at org.jenkinsci.plugins.GithubSecurityRealm.loadUserByUsername(GithubSecurityRealm.java:428)
    at hudson.model.User.impersonate(User.java:254)
    at jenkins.security.ApiTokenFilter.doFilter(ApiTokenFilter.java:52)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
    at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:66)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
    at winstone.FilterConfiguration.execute(FilterConfiguration.java:194)
    at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:366)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:50)
    at winstone.FilterConfiguration.execute(FilterConfiguration.java:194)
    at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:366)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
    at winstone.FilterConfiguration.execute(FilterConfiguration.java:194)
    at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:366)
    at winstone.RequestDispatcher.forward(RequestDispatcher.java:331)
    at winstone.RequestHandlerThread.processRequest(RequestHandlerThread.java:215)
    at winstone.RequestHandlerThread.run(RequestHandlerThread.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
```

Using the version **0.12** of Github OAuth Plugin with Jenkins **1.493**.

#### How to reproduce:
1. Get your api token
2. Execute a request using curl
   
   curl --user username:apiToken "http://jenkins.yourhost.com/job/jobName/lastBuild/api/json?pretty=true"

**Comment by patcon** [comment]
That is REALLY helpful @marcospereira -- I didn't realize those API tokens were an option at all, so at least now I'm on the same page as everyone else experiencing the issue :)

Thanks!

**Comment by tinomen** [comment]
I believe this is related to a pull request that was committed months ago for this. No release has been made at least it's not clear there is an update available from within jenkins. Manual build and install instructions found on the pull request. https://github.com/mocleiri/github-oauth-plugin/issues/18

**Comment by patcon** [comment]
Ah perfect, subscribed :)
